name: Upload My Demo App Daily

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

jobs:
  upload_android:
    name: Upload My Demo App Android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        datacenter: [ eu-central-1, us-west-1 ]
    steps:
      - name: Download My Demo App Android
        uses: wei/curl@v1.1.1
        with:
          args: -L -o SauceLabs-Demo-App.apk https://github.com/saucelabs/my-demo-app-android/releases/download/2.2.0/mda-2.2.0-25.apk
      - name: Upload My Demo App Android
        uses: wei/curl@v1.1.1
        with:
          args: -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location --request POST 'https://api.${{ matrix.datacenter }}.saucelabs.com/v1/storage/upload' --form 'payload=@"SauceLabs-Demo-App.apk"' --form 'name="SauceLabs-Demo-App.apk"'

  upload_ios_zip:
    name: Upload My Demo App iOS zip
    runs-on: ubuntu-latest
    strategy:
      matrix:
        datacenter: [ eu-central-1, us-west-1 ]
    steps:
      - name: Download My Demo App iOS zip
        uses: wei/curl@v1.1.1
        with:
          args: -L -o SauceLabs-Demo-App.Simulator.zip https://github.com/saucelabs/my-demo-app-ios/releases/download/2.0.2/SauceLabs-Demo-App.Simulator.zip
      - name: Upload My Demo App iOS zip
        uses: wei/curl@v1.1.1
        with:
          args: -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location --request POST 'https://api.${{ matrix.datacenter }}.saucelabs.com/v1/storage/upload' --form 'payload=@"SauceLabs-Demo-App.Simulator.zip"' --form 'name="SauceLabs-Demo-App.Simulator.zip"'

  upload_ios_ipa:
    name: Upload My Demo App iOS ipa
    runs-on: ubuntu-latest
    strategy:
      matrix:
        datacenter: [ eu-central-1, us-west-1 ]
    steps:
      - name: Download My Demo App iOS ipa
        uses: wei/curl@v1.1.1
        with:
          args: -L -o SauceLabs-Demo-App.ipa https://github.com/saucelabs/my-demo-app-ios/releases/download/2.0.2/SauceLabs-Demo-App.ipa
      - name: Upload My Demo App iOS ipa
        uses: wei/curl@v1.1.1
        with:
          args: -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location --request POST 'https://api.${{ matrix.datacenter }}.saucelabs.com/v1/storage/upload' --form 'payload=@"SauceLabs-Demo-App.ipa"' --form 'name="SauceLabs-Demo-App.ipa"'

  upload_android_rn:
    name: Upload My Demo App Android RN
    runs-on: ubuntu-latest
    strategy:
      matrix:
        datacenter: [ eu-central-1, us-west-1 ]
    steps:
      - name: Download My Demo App Android RN
        uses: wei/curl@v1.1.1
        with:
          args: -L -o Android.MyDemoAppRN.apk https://github.com/saucelabs/my-demo-app-rn/releases/download/v1.3.0/Android-MyDemoAppRN.1.3.0.build-244.apk
      - name: Upload My Demo App Android RN
        uses: wei/curl@v1.1.1
        with:
          args: -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location --request POST 'https://api.${{ matrix.datacenter }}.saucelabs.com/v1/storage/upload' --form 'payload=@"Android.MyDemoAppRN.apk"' --form 'name="Android.MyDemoAppRN.apk"'

  upload_ios_rn_zip:
    name: Upload My Demo App iOS zip RN
    runs-on: ubuntu-latest
    strategy:
      matrix:
        datacenter: [ eu-central-1, us-west-1 ]
    steps:
      - name: Download My Demo App iOS zip RN
        uses: wei/curl@v1.1.1
        with:
          args: -L -o iOS.MyDemoAppRN.zip https://github.com/saucelabs/my-demo-app-rn/releases/download/v1.3.0/iOS-Simulator-MyRNDemoApp.1.3.0-162.zip
      - name: Upload My Demo App iOS zip RN
        uses: wei/curl@v1.1.1
        with:
          args: -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location --request POST 'https://api.${{ matrix.datacenter }}.saucelabs.com/v1/storage/upload' --form 'payload=@"iOS.MyDemoAppRN.zip"' --form 'name="iOS.MyDemoAppRN.zip"'
